name: CICD workshop
on:
    push:
      branches:
        - main
jobs:
    CICD_workshop:
        runs-on: ubuntu-latest

        steps:
            - name: checkout test
              id: checkout_test
              uses: actions/checkout@v4
            
            - name: run trivy scanner
              id: run_trivy_scanner
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'repository'
                format: 'table'
                exit-code: '1'
                ignore-unfixed: true
                vuln-type: 'os,library'
                severity: 'HIGH'
                output: ${{secrets.TEST_SUBMISSION}}
