name: CICD workshop
on:
    push:
      branches:
          - 'v[0-9]+.[0-9]+'

jobs:
    CICD_workshop:
        runs-on: ubuntu-latest

        steps:
            - name: checkout test
              id: checkout_test
              uses: actions/checkout@v4

            - name: run trivy scanner
              id: run_trivy_scanner
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                ignore-unfixed: true
                format: 'table'
                output: 'trivy-report.txt'
                severity: 'CRITICAL'
                exit-code: '1'

            # - name: trial run
            #   id: trial_run
            #   run: echo "hello" > hello.txt

            - name: list directory
              id: list_directory
              run: echo "$(ls -l)"

            - name: send to slack
              id: send_to_slack
              uses: rtCamp/action-slack-notify@v2
              env:
                SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                SLACK_CHANNEL: general
                SLACK_COLOR: ${{ job.status }}
                SLACK_USERNAME: TestingName
                SLACK_TITLE: Image build and signed
                SLACK_MESSAGE: "test"

            - name: send trivy report
              id: send_trivy_report
              if: failure()
              uses: MeilCli/slack-upload-file@v3
              with:
                slack_token: ${{ secrets.SLACK_TOKEN }}
                channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
                file_path: 'trivy-report.txt'
                initial_comment: 'Scan report by Audrey'    
                
            - name: Install Cosign
              id: install_cosign
              uses: sigstore/cosign-installer@v3.1.1
              with:
                cosign-release: 'v2.1.1'

            - name: Set up QEMU
              id: set_up_qemu
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Build
              id: set_up_docker_build
              uses: docker/setup-buildx-action@v3
              
            - name: Login to Docker Hub
              id: login_to_docker_hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build and push
              id: build_and_push
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: audreyong/go-fortune:6996aa9568c63e698c328b6a94edc3feb8e31ded

            - name: Sign image with key
              id: sign_image_with_key
              run: |
                cosign sign --yes --key env://COSIGN_PRIVATE_KEY audreyong/go-fortune:${{github.sha}}
              env:
                COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
                COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}