name: CICD workshop
on:
    push
jobs:
    CICD_workshop:
        runs-on: ubuntu-latest

        steps:
            - name: checkout test
              id: checkout_test
              uses: actions/checkout@v4
            
            - name: run trivy scanner
              id: run_trivy_scanner
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                scan-ref: '.'
                format: 'table'
                exit-code: '1'
                severity: 'HIGH'
                trivy-config: CICD_workshop.yaml
                
            - name: send message
              id: send_message
              uses: slackapi/slack-github-action@v1.24.0
              env:
                SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}